<svelte:head>
    <title>Glossary of medical abbreviations | mastcell.help | mastcell.help</title>
</svelte:head>

<div class="prose">

<h1 id="glossary-of-medical-abbreviations">Glossary of medical abbreviations</h1>
<ul>
<li>a̅ = before (from Latin “ante”)</li>
<li>accel = acceleration</li>
<li>A&amp;P = anterior &amp; posterior</li>
<li>A.M. = before noon</li>
<li>A/G = Albumin globulin ratio</li>
<li>A2 = Aortic Second sound</li>
<li>AA = Acute Appendectomy</li>
<li>aa = of each, equal parts</li>
<li>AAT = ambulate as tolerated</li>
<li>AB = abortion</li>
<li>abd = abdomen</li>
<li>ABG = arterial blood gases</li>
<li>Abn = abnormal</li>
<li>ABW = adjusted body weight</li>
<li>AC = Air Contrast</li>
<li>A-C = Acromio-clavicular</li>
<li>ACL = Anterior Cruciate Ligament</li>
<li>ad = lib as much as needed, as desired</li>
<li>ADH = anti-diuretic hormone</li>
<li>ADL = Activities of daily living</li>
<li>adm = admission</li>
<li>AFB = acid-fast bacilli</li>
<li>AFI = Amnitotic fluid index</li>
<li>AFib = atrial fibrillation</li>
<li>AFP = alpha fetaprotein</li>
<li>AGA = Appropriate for gestational age</li>
<li>agit. = shake or stir</li>
<li>AgNo3 = Silver Nitrate</li>
<li>AIDS = Acquired Immunodeficiency Syndrome</li>
<li>AK = above-knee</li>
<li>AKA = above-knee amputation</li>
<li>AKI = acute kidney injury</li>
<li>Alb = Albuterol</li>
<li>alb. = albumin</li>
<li>ALD = alcoholic liver disease</li>
<li>ALS = amyotrophic lateral sclerosis</li>
<li>alt. = alternate, alternating</li>
<li>AMA = Against Medical Advice</li>
<li>AMB = ambulatory</li>
<li>AMI = Acute Myocardial Infarction</li>
<li>amnio = amniocentesis</li>
<li>amp = ampule</li>
<li>amt. = amount</li>
<li>AMU = Acute Medical Unit</li>
<li>ant. = anterior</li>
<li>ante = before</li>
<li>AODM = Adult Onset Diabetes Mellitus</li>
<li>approx = approximately</li>
<li>appt = appointment</li>
<li>Appy = appendectomy</li>
<li>aq = water</li>
<li>aq. = dest distilled water</li>
<li>ARDS = Adult respiratory distress syndrome</li>
<li>AROM = Artificial rupture of membranes</li>
<li>ASA = Aspirin</li>
<li>ASCVD = Arteriosclerotic cardiovascular disease</li>
<li>ASD = atrial septal defect</li>
<li>ASHD = arteriosclerotic heart disease</li>
<li>ASIS = anterior superior iliac spine</li>
<li>asst = assistance</li>
<li>ASU = Acute Surgical Unit</li>
<li>ATach = Atrial Tachycardia</li>
<li>Aug = Augmentation</li>
<li>AV = atriovenous</li>
<li>avg = average</li>
<li>AVN = atrioventricular node</li>
<li>AVSS = afebrile, vital signs stable</li>
<li>b.i.d. = twice daily</li>
<li>B.O.M. = bilateral otitis media</li>
<li>B1 = thiamin</li>
<li>B2 = Riboflavin</li>
<li>BBB = Bundle Branch Block</li>
<li>BE = barium enema</li>
<li>BF = breast feeding</li>
<li>bil. = bilateral</li>
<li>bili = bilirubin</li>
<li>BK = below-knee</li>
<li>BKA = Below knee amputation</li>
<li>Bl. = bleeding</li>
<li>BM = Bowel Movement</li>
<li>BMI = Body Mass Index</li>
<li>BMP = Basic Metabolic Panel</li>
<li>BMR = basal metabolic rate</li>
<li>BOA = born out of asepsis</li>
<li>BOM = Bilateral Otitis Media</li>
<li>BOW = Bag of Water</li>
<li>BP = blood pressure</li>
<li>BPH = benign prostatic hypertrophy</li>
<li>BPP = Biophysical Profile</li>
<li>BR = Bathroom</li>
<li>brady = bradycardia</li>
<li>BRB = bright red blood</li>
<li>Brk = Bronkosol</li>
<li>BRP = bathroom privileges</li>
<li>BS = blood sugar</li>
<li>BSA = body surface area</li>
<li>BSC = bedside commode</li>
<li>BSE = breast self-exam</li>
<li>BSER = brain stem evoked response</li>
<li>BSN = Bachelor of Science, Nursing</li>
<li>BSO = bilateral salpingo-oophorectomy</li>
<li>BST = Breast stimulation test</li>
<li>BUE = bilateral upper extremity</li>
<li>BUN = blood urea nitrogen</li>
<li>BVM = bag value mask</li>
<li>BVT = bag value tube</li>
<li>Bx = biopsy</li>
<li>C̅ = with</li>
<li>C = centigrade</li>
<li>C&amp;S = culture and sensitivity</li>
<li>c&amp;v = cupping &amp; vibration</li>
<li>C.O. = Cardiac output</li>
<li>C.S.M. = circulation, sensation and motion</li>
<li>c/o = complaining of</li>
<li>C/S = Cesarean section</li>
<li>C/W = consistent with</li>
<li>CA = carcinoma, cancer</li>
<li>Ca++ = Calcium</li>
<li>CABG = coronary artery bypass graft</li>
<li>CAD = coronary artery disease</li>
<li>Cal = calorie</li>
<li>CAN = cord around neck</li>
<li>Caps = capsule</li>
<li>CAT = Computerized Axial Tomography</li>
<li>cath = catheterization</li>
<li>CBC = complete blood count</li>
<li>CBR = complete bed rest</li>
<li>CBS = chronic brain syndrome</li>
<li>CCU = Coronary Care Unit</li>
<li>CDC = Center for Disease Control</li>
<li>CEA = carcinoembryonic antigen</li>
<li><ol start="900" type="i">
<li>= centimeter</li>
</ol></li>
<li>CHB = complete heart block</li>
<li>CHD = Congenital heart disease</li>
<li>CHF = Congestive Heart Failure</li>
<li>chg = change</li>
<li>chol = cholesterol</li>
<li>CI = coronary insufficiency</li>
<li>circ. = circumcision</li>
<li>cl = clear</li>
<li>CL = chloride</li>
<li>Cl. = Liq. clear liquids</li>
<li>Cl. = Time clotting time</li>
<li>cldy = cloudy</li>
<li>cm = H20 centimeters of water pressure</li>
<li>CMML = Chronic myelomonocytic leukemia</li>
<li>CMS = Circulation, motion, and sensation</li>
<li>CNA = certified nurses aide</li>
<li>CNS = central nervous system</li>
<li>CO2 = carbon dioxide</li>
<li>cocci = coccidioidomycosis</li>
<li>comp. = compound</li>
<li>conc. = concentrated</li>
<li>conf = conference</li>
<li>cong = congested</li>
<li>cont. = continued</li>
<li>Cont.aero = Continuous Aerosol</li>
<li>COPD = chronic obstructive pulmonary disease</li>
<li>CPAP = continuous positive airway pressure</li>
<li>CPD = cephalopelvic disproportion</li>
<li>CPK = creatinine phosphokinase</li>
<li>CPM = continuous passive motion</li>
<li>CPR = cardiopulmonary resuscitation</li>
<li>CPT = Chest Physiotherapy</li>
<li>CRAMS = Circulation, Respiration, Abdomen, Motor, Speech</li>
<li>CRNA = Certified Registered Nurse Anesthetist</li>
<li>CRP = C-Reactive protein</li>
<li>CS = Central Supply</li>
<li>CSF = cerebrospinal fluid</li>
<li>CSP = Central Sterile Processing</li>
<li>CST = contraction stimulation test</li>
<li>CT = computerized tomography</li>
<li>CTA = clear to auscultation</li>
<li>ctx = cervical traction</li>
<li>Cu = copper</li>
<li>cu. = mm. cubic millimeter</li>
<li>CV = cardiovascular</li>
<li>CVA = cerebrovascular accident</li>
<li>CVC = central venous catheter</li>
<li>CVP = central venous pressure</li>
<li>CXR = chest x-ray</li>
<li>CTR = Carpal tunnel release</li>
<li>D&amp;C = dilatation and curettage</li>
<li>D.O.E. = dyspnea on exertion</li>
<li>D.O.S. = Day of surgery</li>
<li>D.R. = Delivery Room</li>
<li>D.T. = delirium tremens</li>
<li>D.W. = distilled water</li>
<li>d/c-dc = discontinue</li>
<li>D/RL = dextrose and Ringer’s Lactate</li>
<li>D/W = dextrose and water</li>
<li>D5LR = 5 percent dextrose Lactated Ringers</li>
<li>D5W = 5% dextrose in water</li>
<li>DAT = diet as tolerated</li>
<li>DBP = diastolic blood pressure</li>
<li>DDI = dressing dry &amp; intact</li>
<li>Decel = decleeration</li>
<li>decr = decrease or diminish</li>
<li>decub = decubitus</li>
<li>defib = defibrillation</li>
<li>dept = department</li>
<li>DES = Diethylstilbestrol</li>
<li>dev = seq developmental sequences</li>
<li>DFA = diet for age</li>
<li>diag = diagnosis</li>
<li>diam = diameter</li>
<li>DIC = disseminated intravascular coagulopathy</li>
<li>dil. = dilute or dissolve</li>
<li>DIP = distal interphalangeal joint</li>
<li>disch = discharge</li>
<li>DISH = Diffuse idiopathic skeletal hyperostosis</li>
<li>disp = dispense</li>
<li>div = divide</li>
<li>DJD = Degenerative Joint Disease</li>
<li>DKA = Diabetic Ketoacidosis</li>
<li>DLCO = Diffusion capacity of lung</li>
<li>DM = Diabetes Mellitus</li>
<li>DME = Durable medical equipment</li>
<li>DNR = Do not resuscitate</li>
<li>DO = Doctor of Osteopathy</li>
<li>DOA = Dead on Arrival</li>
<li>DOB = Date of Birth</li>
<li>DR = Doctor</li>
<li>dr. = dram</li>
<li>drng = drainage</li>
<li>drsg = dressing</li>
<li>DSD = dry sterile dressing</li>
<li>DSE = daily skills evaluation</li>
<li>DU = duodenal ulcer</li>
<li>DUB = dysfunctional uterine bleeding</li>
<li>DVT = Deep Venous Thrombosis</li>
<li>DX = Diagnosis</li>
<li>E. = Coli Escherichia coli</li>
<li>e.g. = for example</li>
<li>E.S. = electrical stimulation</li>
<li>EBL = Estimated blood loss</li>
<li>ECCE = Extracapsular Cataract Extraction</li>
<li>ECG = Electrocardiogram</li>
<li>ED = Emergency Department</li>
<li>EDC = Estimated date of confinement</li>
<li>EDC = Estimated date of conception</li>
<li>EDD = end diastolic diameter</li>
<li>EDP = end diastolic pressure</li>
<li>EEG = Electroencephalogram</li>
<li>EENT = Ears, eyes, nose &amp; throat</li>
<li>eff = effective</li>
<li>EFM = external fetal monitor</li>
<li>EGA = estimated gestational age</li>
<li>EGD = esophagogastroduodenoscopy</li>
<li>EKG = Electrocardiogram</li>
<li>elix = elixir</li>
<li>EMG = electromyogram</li>
<li>Enf = Enfamil</li>
<li>ENG = electronystagmography</li>
<li>ENT = Ears, nose &amp; throat</li>
<li>EOA = esophageal obturator airway</li>
<li>EOM = extraocular muscles</li>
<li>EPID = epidural</li>
<li>EPIS = episiotomy</li>
<li>Eq = Su equipment set-up</li>
<li>ERCP = endoscopic retrograde cholangiopancreatography</li>
<li>ERV = expiratory reserve volume</li>
<li>ESD = end systolic diameter</li>
<li>ESR = Erythrocyte sedimentation rate</li>
<li>est. = estimate</li>
<li>ET = Endotracheal</li>
<li>et. = and</li>
<li>etiol = etiology</li>
<li>ETOH = Ethyl alcohol</li>
<li>ETT = endotracheal tube</li>
<li>EUA = examination under anesthesia</li>
<li>eval = evaluation</li>
<li>ex = excision</li>
<li>exer. = exercise</li>
<li>Exp. = Expired</li>
<li>Exp. = Lap Exploratory laparotomy</li>
<li>expl. = exploratory</li>
<li>ext. = external</li>
<li>F = Fahrenheit</li>
<li>F.F. = force fluids</li>
<li>F.F.P. = fresh frozen plasma</li>
<li>f.o.b. = foot of bed</li>
<li>F/U = Follow-up</li>
<li>FACH = forceps after coming head</li>
<li>FAS = fetal alcohol syndrome</li>
<li>FB = foreign body</li>
<li>FBS = fasting blood sugar</li>
<li>FDA = Food &amp; Drug Administration</li>
<li>fdg = feeding</li>
<li>fe = female</li>
<li>Fe = iron</li>
<li>FH = family history</li>
<li>FHM = fetal heart monitor</li>
<li>FHR = fetal heart rate</li>
<li>FHT = fetal heart tones</li>
<li>Fi02 = oxygen percentage</li>
<li>fib = fibrillation</li>
<li>fl. = fluid</li>
<li>Fl. = dr. fluid dram</li>
<li>fl. = oz. fluid ounce</li>
<li>FM = fetal movement</li>
<li>FMC = Family Maternity Center</li>
<li>FP = Family Practice</li>
<li>FPL = flexor pollicus longus</li>
<li>FRC = functional residual capacity</li>
<li>Freq = frequency</li>
<li>FSE = fetal scalp electrode</li>
<li>FSH = follicle stimulating hormone</li>
<li>ft. = foot</li>
<li>FTSG = full-thickness skin graft</li>
<li>FUO = fever of undetermined origin</li>
<li>FVC = forced vital capacity</li>
<li>FWB = full weight bearing</li>
<li>fx = fracture</li>
<li>G/S = glucose and saline</li>
<li>G/W = glucose and water</li>
<li>GA = gestational assessment</li>
<li>gal = gallon</li>
<li>gastroc = gastrocnemius</li>
<li>GB = gallbladder</li>
<li>GBS = Group B strep</li>
<li>GDM = gestational diabetes mellitus</li>
<li>GERD = gastro esophageal reflux disease</li>
<li>GGT = gamma glutamyl transferase</li>
<li>G-Hgb = glycosylated hemoglobin</li>
<li>GI = gastrointestinal</li>
<li>GLU = glucose</li>
<li>glut = gluteal</li>
<li>gm = gram</li>
<li>gm% = grams percent</li>
<li>GN = graduate nurse</li>
<li>GPN = graduate practical nurse</li>
<li>gr = grain</li>
<li>Grav, = Gr Gravida</li>
<li>gt = drop</li>
<li>gtt = drops</li>
<li>GTT = Glucose Tolerance Test</li>
<li>GU = genitourinary</li>
<li>GYN = gynecology</li>
<li>H&amp;H = Hemoglobin &amp; Hematocrit</li>
<li>H&amp;L = heart and lungs</li>
<li>H&amp;P = history and physical</li>
<li>H202 = hydrogen peroxide</li>
<li>H2O = water</li>
<li>HA = headache</li>
<li>HAE = hearing aid evaluation</li>
<li>HASHD = Hypertensive arteriosclerotic heart disease</li>
<li>HAT = Hemovac Auto Transfuser</li>
<li>HbA = glycosylated hemoglobin</li>
<li>HBIG = Hepatitis B Immune Globulin</li>
<li>HBP = High Blood Pressure</li>
<li>HbSAb = Hepatitis B surface antibody</li>
<li>HbSAg = Hepatitis B surface antigen</li>
<li>HC = head circumference</li>
<li>HCG = human chorionic gonadotropin</li>
<li>HCO3 = bicarbonate</li>
<li>HCVD = Hypertensive Cardiovascular disease</li>
<li>HDL = high density liquid protein</li>
<li>HEENT = head, eyes, ears, nose &amp; throat</li>
<li>HELLP = hemolysis, elevated liver enzymes &amp; low platelet syndrome</li>
<li>hemi = half</li>
<li>Hep = B Hepatitis B</li>
<li>Hep = L,HL Heparin lock</li>
<li>HF = Heparin flush</li>
<li>HFP = High Fowler’s position</li>
<li>Hg = mercury</li>
<li>Hgb = hemoglobin</li>
<li>HHD = Hypertensive heart disease</li>
<li>HHN = hand held nebulizer</li>
<li>HIDA = hepato-iminodiacetic acid</li>
<li>histo = histoplasmin</li>
<li>HIV = Human Immunodeficiency virus</li>
<li>HMD = Hyaline Membrane Disease</li>
<li>HNP = herniated nucleus pulposus</li>
<li>HOB = head of bed</li>
<li>hp = hot pack</li>
<li>HPI = history of present illness</li>
<li>HPTN = hypertension</li>
<li>HR = heart rate</li>
<li>hr,h = hour</li>
<li>HSP = Henoch-Schönlein purpura</li>
<li>HSV = herpes simplex viruses</li>
<li>HT = Hubbard Tank</li>
<li>Ht. = height</li>
<li>HTN = Hypertension</li>
<li>HWP = home walking program</li>
<li>hx = history</li>
<li>hypo = hypodermically</li>
<li>hyst. = hysterectomy</li>
<li>I = Iodine</li>
<li>I&amp;D = incision and drainage</li>
<li>I&amp;O = intake and output</li>
<li>i.e. = that is</li>
<li>I.V. = intravenous</li>
<li>I:E = Inspiratory time to Expiratory time ration</li>
<li>IABP = Intra-aortic Balloon Pump</li>
<li>IBW = Ideal Body Weight</li>
<li>IC = intracardiac</li>
<li>ICP = intracranial pressure</li>
<li>ICPM = intracranial pressure monitoring</li>
<li>ICU = Intensive Care Unit</li>
<li>id. = the same</li>
<li>IDDM = Insulin-dependent diabetes mellitus</li>
<li>IDM = infant of diabetic mother</li>
<li>IFM = internal fetal monitor</li>
<li>IM = intramuscular</li>
<li>IMI = Inferior Myocardial Infarction</li>
<li>IMV = Intermittent Mandatory Ventilation</li>
<li>inc. = incontinent</li>
<li>incr = increase</li>
<li>Ind = induction</li>
<li>indep = independent</li>
<li>inf = infection</li>
<li>init = initials</li>
<li>inj = injection</li>
<li>INR = International Normalization Ratio</li>
<li>ins = insurance</li>
<li>insp. = inspiratory</li>
<li>instr. = instructions</li>
<li>int. = internal</li>
<li>invol = involuntary</li>
<li>IOL = Intraocular lens</li>
<li>IOP = intraocular pressure</li>
<li>IP = inpatient</li>
<li>IPG = Impedence Phlebograph</li>
<li>IPPB = intermittent positive pressure breathing</li>
<li>IQ = intelligence quotient</li>
<li>IRV = inspiratory reserve volume</li>
<li>IS = incentive spirometry</li>
<li>iso = isoenzymeisol</li>
<li>Isol. = isolation</li>
<li>Isup = Isuprel</li>
<li>ITP = Idiopathic thrombocytopenic purpura</li>
<li>IUC = intrauterine catheter</li>
<li>IUD = intrauterine device</li>
<li>IUGR = intrauterine growth retardation</li>
<li>IUPC = intrauterine pressure catheter</li>
<li>IVAC = intravenous infusion pump</li>
<li>IVCD = intraventricular conduction defect</li>
<li>IVP = intravenous pyelogram</li>
<li>IVPB = intravenous piggyback</li>
<li>IV-push = intravenous push</li>
<li>IVU = intravenous urogram</li>
<li>IWMI = Inferior Wall Myocardial Infarction</li>
<li>JDM = juvenile diabetes mellitus</li>
<li>jt. = joint</li>
<li>JVD = jugular vein distention</li>
<li>JVP = jugular venous pulse</li>
<li>K,K+ = potassium</li>
<li>K.O. = keep open</li>
<li>KCL = potassium chloride</li>
<li>Kg = kilogram</li>
<li>KI = potassium iodine</li>
<li>KJ = knee jerks</li>
<li>KLS = kidney, liver, spleen</li>
<li>KPM = kilopound meter</li>
<li>KUB = kidney, ureter, bladder</li>
<li>Kv. = kilivolts</li>
<li>KVO = keep vein open</li>
<li>l = liter</li>
<li>L = left</li>
<li>LL = left lateral</li>
<li>l&amp;w = living and well</li>
<li>L.E. = Lupus Erythematosis</li>
<li>L.M.L. = left middle lobe</li>
<li>L/D = Labor &amp; Delivery</li>
<li>L/S = lumbosacral</li>
<li>L/S = ratio lecithin/sphingomyelin ratio</li>
<li>LA = left arm</li>
<li>LA = line left atrial line</li>
<li>lab = laboratory</li>
<li>lac = laceration</li>
<li>LAC = long arm cast</li>
<li>LAD = left anterior descending</li>
<li>LAE = left atrial enlargement</li>
<li>lang = language</li>
<li>LAP = left atrial pressure</li>
<li>LASER = light amplification by stimulated emission of radiation</li>
<li>lat = lateral</li>
<li>LAT = left anterior thigh</li>
<li>lb. = pound</li>
<li>LBBB = left bundle branch block</li>
<li>LBP = low blood pressure</li>
<li>LBW = low birth weight</li>
<li>LCL = lateral cruciate ligament</li>
<li>LD = left deltoid</li>
<li>LDH = lactic dehydrogenase</li>
<li>LDL = low density liquid protein</li>
<li>LDR = Labor Delivery Recovery</li>
<li>LDRP = Labor Delivery Recovery Postpartum</li>
<li>LE = lower extremity</li>
<li>LEEP = Loop electrocautery excision procedure</li>
<li>LFA(RFA) = left frontoanterior (right)</li>
<li>LFP = (RFP) left frontoposterior (right)</li>
<li>LFT = (RFT) left frontotransverse (right)</li>
<li>LG = left gluteus</li>
<li>lg. = large</li>
<li>LGA = large for gestational age</li>
<li>liq. = liquid</li>
<li>LKS = liver, kidneys, spleen</li>
<li>LL = Left lateral</li>
<li>LLC = long leg cast</li>
<li>LLE = left lower extremity</li>
<li>LLL = left lower lobe</li>
<li>LLQ = left lower quadrant of abdomen</li>
<li>LLSB = lower left sternal border</li>
<li>LMA = (RMA) left mentoanterior (right)</li>
<li>LML = left medial lateral</li>
<li>LMP = last menstrual period</li>
<li>LMT = (RMT) left mentotransverse (right)</li>
<li>LOA = Left Occiput Anterior</li>
<li>LOA = Leave of Absence</li>
<li>LOC = level of consciousness</li>
<li>LOP = left occiput posterior</li>
<li>LOS = length of stay</li>
<li>LOT = left occiput transverse</li>
<li>LP = lumbar puncture</li>
<li>lpm = liters per minute</li>
<li>LPN = Licensed Practical Nurse</li>
<li>LR = lactated ringers</li>
<li>LSA(RSA) = left sacrum anterior (right)</li>
<li>LSB = left sternal border</li>
<li>LSO = left salpingo-oophorectomy</li>
<li>LSP = (RSP) left sacrum posterior (right)</li>
<li>LST(RST) = left sacrum transverse (right)</li>
<li>Lt. = L left leg</li>
<li>LTB = laryngotracheo bronchitis</li>
<li>LTCS = low transverse Cesarean section</li>
<li>LTG = long term goals</li>
<li>LTM = long term memory</li>
<li>LTV = long term variability</li>
<li>LUAQ = left upper abdominal quadrant</li>
<li>LUE = left upper extremity</li>
<li>LUL = left upper lobe</li>
<li>LUOQ = left upper outer quadrant of gluteal area</li>
<li>LUQ = left upper quadrant</li>
<li>LV = left ventricle</li>
<li>LVE = left ventricular enlargement</li>
<li>LVEDP = left ventricle and diastolic pressure</li>
<li>LVET = left ventricular ejection time</li>
<li>LVG = left ventrogluteal area</li>
<li>LVH = left ventricular hypertrophy</li>
<li>LVL = left vastus lateralis</li>
<li>LVN = Licensed Vocational Nurse</li>
<li>LVPW = left ventricular posterior wall</li>
<li>LVSV = left ventricle stroke volume</li>
<li>LVSW = left ventricle stroke work</li>
<li>m = meter</li>
<li>ma = male</li>
<li>m.s. = morphine sulphate</li>
<li>MAP = mean airway pressure</li>
<li>MAS = mobile arm support</li>
<li>max = maximum</li>
<li>MBU = Mom/Baby Unit</li>
<li>mcgm = microgram</li>
<li>mcgtts = microdrops</li>
<li>MCL = medial collateral ligament</li>
<li>MCP = metacarpal interphalangeal joint</li>
<li>MD = Medical Doctor</li>
<li>MDI = Metered dose inhaler</li>
<li>mech = mechanical</li>
<li>med = medication</li>
<li>MEF = maximal mid-expiratory flow</li>
<li>mEq = milliequivalent</li>
<li>mg = milligram</li>
<li>Mg = Magnesium</li>
<li>Mg/dl = milligrams per deciliter</li>
<li>MH = medical history</li>
<li>MI = Myocardial Infarction</li>
<li>ml = milliliter</li>
<li>ML = midline</li>
<li>mm = millimeter</li>
<li>mm1hg = millimeters of mercury</li>
<li>mm3 = millimeter cubed</li>
<li>MMK = Marshall-Marchetti-Krantz</li>
<li>MMPI = Minnesota Multiphasic Personality Inventory</li>
<li>MMR = mumps, measles, rubella</li>
<li>MMT = manual muscle test</li>
<li>MMW = Marshall-Marchetti-Weiss</li>
<li>mod = moderate</li>
<li>MOM = Milk of Magnesia</li>
<li>Mono = mononucleosis</li>
<li>MP = metabolic panel</li>
<li>mph = miles per hour</li>
<li>MRMI = Mental Retardation, Mental Illness</li>
<li>MS = Multiple Sclerosis</li>
<li>mtg = meeting</li>
<li>MTP = metatarsophalangeal</li>
<li>mult = multiples</li>
<li>MV = mitral valve</li>
<li>MVA = motor vehicle accident</li>
<li>MVP = mitral valve prolapse</li>
<li>MVR = mitral valve regurgitation</li>
<li>N = normal</li>
<li>N/A = not applicable</li>
<li>N/C = no complaints</li>
<li>N/V = nausea and vomiting</li>
<li>NA = Nurses Aide</li>
<li>Na+,Na = sodium</li>
<li>NaCl = sodium chloride</li>
<li>NB = newborn</li>
<li>NC = nasal cannula</li>
<li>neg = negative</li>
<li>Neuro = Neurology</li>
<li>NG = nasogastric</li>
<li>NG = tube nasogastric tube</li>
<li>Ng/ml = nanogram/milliliter</li>
<li>NICU = Neonatal Intensive Care Unit</li>
<li>NIDDM = non-insulin dependent diabetes mellitus</li>
<li>NIF = negative inspiratory force</li>
<li>NKA = no known allergies</li>
<li>NKDA = No known drug allergies</li>
<li>NKMA = no known medication allergies</li>
<li>NM = nanometer</li>
<li>NNP = Neonatal Nurse Practitioner</li>
<li>no. = number</li>
<li>noc = night</li>
<li>NP = Neuropsychiatric</li>
<li>NPH = Type of Insulin (Isophane)</li>
<li>NPN = nonprotein nitrogen</li>
<li>NPO = nothing by mouth</li>
<li>NR = do not repeat</li>
<li>NS = normal saline</li>
<li>NSL = normal saline lock</li>
<li>NSAID = Non-steroidal Anti-inflammatory Drug</li>
<li>NSR = normal sinus rhythm</li>
<li>NST = non-stress test</li>
<li>NSU = non-specific urethritis</li>
<li>NSY = Nursery</li>
<li>NTG = nitroglycerine</li>
<li>NVD = neck vein distention</li>
<li>NWB = non weight bearing</li>
<li>NYD = not yet diagnosed</li>
<li>O&amp;P = Ova &amp; Parasites</li>
<li>o.c. = open crib</li>
<li>O.D. = right eye</li>
<li>O.S. = left eye</li>
<li>O.U. = both eyes</li>
<li>O2 = Oxygen</li>
<li>OA = occiput anterior</li>
<li>OB = Obstetrics</li>
<li>obl = oblique</li>
<li>OBS = Organic Brain Syndrome</li>
<li>OC = oral contraceptive</li>
<li>OCT = oxytocin challenge test</li>
<li>OFC = occipitofrontal circumference</li>
<li>OOB = out of bed</li>
<li>OP = Outpatient</li>
<li>OPD = Outpatient Department</li>
<li>OPG = oculoplethysmography</li>
<li>OR = Operating Room</li>
<li>ORIF = open reduction, internal fixation</li>
<li>Ortho = Orthopedics</li>
<li>OSA = Obstructed sleep apnea</li>
<li>OT = Occupational Therapy</li>
<li>oz. = ounce</li>
<li>p̅ = after (from Latin “post”)</li>
<li>P = pulse</li>
<li>P = ox chk pulse oximeter check</li>
<li>p = ox cont. pulse oximeter continuous</li>
<li>P&amp;A = percussion &amp; auscultation</li>
<li>p.c. = after meals</li>
<li>P.E. = physical examination</li>
<li>P.I. = present illness</li>
<li>p.m. = afternoon</li>
<li>P.R.O.M. = partial range of motion</li>
<li>P.S.P. = Phenolsulfonphthalein test</li>
<li>P.T. = physical therapy</li>
<li>PA = pulmonary artery</li>
<li>PAC = premature atrial contraction</li>
<li>PACU = Post-Anesthesia Care Unit</li>
<li>PACU = Post Anesthesia Care Unit</li>
<li>Pap = Papanicolaou smear</li>
<li>PAP = pulmonary arterial pressure</li>
<li>PAR = postanesthesia recovery</li>
<li>para = number of births</li>
<li>PAT = paroxysmal atrial tachycardia</li>
<li>Path = pathology</li>
<li>PAWP = pulmonary artery wedge pressure</li>
<li>PB = barometric pressure</li>
<li>PBI = protein bound iodine</li>
<li>PBP = peak blood pressure</li>
<li>PC = packed cells</li>
<li>PCA = patient controlled analgesia</li>
<li>PCL = posterior cruciate ligament</li>
<li>PCN = penicillin</li>
<li>PCP = Primary Care Physician</li>
<li>PCW = pulmonary capillary wedge</li>
<li>PCXR = portable chest x-ray</li>
<li>PD = postural drainage</li>
<li>PE = pulmonary embolism</li>
<li>Peds = Pediatrics</li>
<li>PEEP = positive and expiratory pressure</li>
<li>PEF = positive expiratory force</li>
<li>PEFR = peak expiratory flow rate</li>
<li>PEG = percutaneous endoscopic gastrostomy</li>
<li>PEP = Positive Expiratory Pressure</li>
<li>PERLA = pupils equal reactive to light and accommodation</li>
<li>PFC = persistent fetal circulation</li>
<li>PFT = pulmonary function test</li>
<li>PG = phosphatidyl glycerol</li>
<li>pH = hydrogen ion concentration</li>
<li>PH = past history</li>
<li>PHR = peak heart rate</li>
<li>PI = phosphatydinnositol</li>
<li>PICC = Peripherally-inserted central catheter</li>
<li>PID = pelvic inflammatory disease</li>
<li>PIH = pregnancy induced hypertension</li>
<li>PIP = proximal interphalangeal</li>
<li>pit = pitocin</li>
<li>PJC = premature junctional contraction</li>
<li>PKU = phenylketonuria</li>
<li>PMH = past medical history</li>
<li>PMI = point of maximum impulse</li>
<li>PMS = premenstrual syndrome</li>
<li>PNA = pneumonia</li>
<li>po = by mouth</li>
<li>POD = Post Op Day</li>
<li>POP = persistent occipitoposterior</li>
<li>pos = positive</li>
<li>PP = postpartum</li>
<li>PPBS = post-prandial blood sugar</li>
<li>PPD = purified protein derivative</li>
<li>PPT = partial prothrombin time</li>
<li>PPTL = Postpartum tubal ligation</li>
<li>PRBC = packed red blood cells</li>
<li>prep = prepare for</li>
<li>PRN = as necessary</li>
<li>Pro. = Prosobee</li>
<li>PROM = premature rupture of membranes</li>
<li>Pro-time = prothrombin time</li>
<li>PS = Pressure Support</li>
<li>PSA = prostatic specific antigen</li>
<li>PSIS = posterior superior iliac spine</li>
<li>psych = psychology</li>
<li>PT = prothrombin time</li>
<li>PTA = prior to arrival</li>
<li>PTCA = Percutaneous transluminal coronary angioplasty</li>
<li>PTSD = Posttraumatic stress disorder</li>
<li>PTT = partial thromboplastin time</li>
<li>pud = pudendal</li>
<li>PUD = Peptic ulcer disease</li>
<li>pulm = pulmonary</li>
<li>pulse = AP apical pulse</li>
<li>Pulse = R radial pulse</li>
<li>Pulv. = powder</li>
<li>PUW = pick up walker</li>
<li>PV = pulmonary valve</li>
<li>PVC = premature ventricular contraction</li>
<li>PVD = peripheral vascular disease</li>
<li>PVR = pulmonary vascular resistance</li>
<li>PWB = partial weight bearing</li>
<li>q = every</li>
<li>q2h = every 2 hours</li>
<li>qh = every hour</li>
<li>qid = four times a day</li>
<li>QNS = quantity not sufficient</li>
<li>QS = quantity sufficient</li>
<li>qt. = quart</li>
<li>quad = quadriplegia</li>
<li>quads = quadriceps</li>
<li>qv = as much as you wish</li>
<li>R = right</li>
<li>R.O.M. = range of motion</li>
<li>R/O = rule out</li>
<li>RA = room air</li>
<li>RAT = right anterior thigh</li>
<li>RBBB = right bundle branch block</li>
<li>rbc = red blood cells</li>
<li>RBC = red blood count</li>
<li>RBP = resting blood pressure</li>
<li>RCP = Respiratory Care Practitioner</li>
<li>RD = right deltoid</li>
<li>RDS = respiratory distress syndrome</li>
<li>ref = refused</li>
<li>REM = rapid eye movement</li>
<li>reps = repetitions</li>
<li>res = residual</li>
<li>resp = respiration</li>
<li>resus = resuscitation</li>
<li>RF = rheumatoid arthritis factor</li>
<li>RG = right gluteus</li>
<li>Rh = Rhesus blood factor</li>
<li>RHD = rheumatic heart disease</li>
<li>RHR = resting heart rate</li>
<li>RL = right lateral</li>
<li>RLE = right lower extremity</li>
<li>RLL = right lower lobe</li>
<li>RLQ = right lower quadrant</li>
<li>rm = room</li>
<li>RML = right middle lobe</li>
<li>RN = Registered Nurse</li>
<li>ROA = right occiput anterior</li>
<li>ROM = rupture of membranes</li>
<li>ROP = right occiput posterior</li>
<li>ROS = review of systems</li>
<li>ROT = right occiput transverse</li>
<li>RPh = Registered Pharmacist</li>
<li>RPR = rapid plasma reagin</li>
<li>Rpt = repeat</li>
<li>RR = Recovery Room</li>
<li>RRR = regular rhythm, rate</li>
<li>RSA = right sacral anterior</li>
<li>RSB = right sternal border</li>
<li>RSO = right salpingo-oophorectomy</li>
<li>RSR = regular sinus rhythm</li>
<li>RSV = Respiratory Syncytial Virus</li>
<li>RT = Respiratory Therapy</li>
<li>Rt.L = right leg</li>
<li>RTC = return to clinic</li>
<li>Rx = prescription</li>
<li>s̅ = without (from Latin “sine”)</li>
<li>S.G. = specific gravity</li>
<li>S/P = status post</li>
<li>S/P = O2 special Oxygen</li>
<li>SAA = same as above</li>
<li>SAB = spontaneous abortion</li>
<li>SaO2 = Oxygen Saturation</li>
<li>SCN = Special Care Nursery</li>
<li>SE = spiral electrode</li>
<li>SF = Semi fowlers</li>
<li>SGOT = serum glutamic oxaloacetic transaminase</li>
<li>SGPT = serum glutamic pyruvic transaminase</li>
<li>SIDS = Sudden Infant Death Syndrome</li>
<li>Sig. = let it be labeled</li>
<li>Sim. = Similac</li>
<li>SIMV = Synchronous Intermittent Mandatory Ventilation</li>
<li>SL = saline lock</li>
<li>SLE = Systemic Lupus Erythematosus</li>
<li>SMAC = lab profile study</li>
<li>SN = student nurse</li>
<li>SOB = shortness of breath</li>
<li>Sol = solution</li>
<li>SOP = standard operating procedure</li>
<li>SOS = one dose only</li>
<li>sp. = gr. specific gravity</li>
<li>spu = ind Sputum Induction</li>
<li>SR = Sinus rhythm</li>
<li>SROM = spontaneous rupture of membranes</li>
<li>s/s = signs and symptoms</li>
<li>SSE = Soapsuds enema</li>
<li>ST = Sinus tachycardia</li>
<li>Staph = Staphylococcus</li>
<li>stat = at once, immediately</li>
<li>STD = sexually transmitted disease</li>
<li>Stim. = Stimulation</li>
<li>Str = strong</li>
<li>Strep = Streptococcus</li>
<li>STV = short term variability</li>
<li>subq = subcutaneous</li>
<li>supp. = suppository</li>
<li>Surg. = Surgery</li>
<li>SVD = single vaginal delivery</li>
<li>SVN = small volume nebulizer</li>
<li>syr. = syrup</li>
<li>T = temperature</li>
<li>T#3 = Tylenol #3</li>
<li>T&amp;A = tonsillectomy &amp; adenoidectomy</li>
<li>T&amp;S = type and screen</li>
<li>t.i.d. = three times a day</li>
<li>T.O. = telephone order</li>
<li>T.P. = Total protein</li>
<li>tab = tablet</li>
<li>TAB = Therapeutic abortion</li>
<li>TAH = Total Abdominal Hysterectomy</li>
<li>TB = Tuberculosis</li>
<li>Tbsp = tablespoon</li>
<li>temp = temperature</li>
<li>Tet = Tetanus</li>
<li>THA = Total Hip Arthroplasty</li>
<li>TIA = Transient Ischemic Attack</li>
<li>TIBC = Total iron binding capacity</li>
<li>TKA = Total knee arthroplasty</li>
<li>TKO = To keep open</li>
<li>TMJ = Temporomandibular joint</li>
<li>TOCO = tocometer</li>
<li>Top = topically</li>
<li>TORCH = toxoplasmosis, other, rubella virus, cytomegalovirus</li>
<li>TPN = Total Parenteral nutrition</li>
<li>TPR = temperature, pulse, respiration</li>
<li>tr. = tincture</li>
<li>tsp. = teaspoon</li>
<li>TTP = Thrombotic Thrombocytopenic Purpura</li>
<li>TUR = Transurethral resection</li>
<li>TURP = Transurethral resection of prostate</li>
<li>TVH = Total Vaginal Hysterectomy</li>
<li>TVTO = tension free transvaginal tape – obturator approach</li>
<li>TX = treatment</li>
<li>U.S.P. = United States Pharmacopecia</li>
<li>UA = urinalysis</li>
<li>UAC = umbilical artery catheter</li>
<li>UC = Uterine Contractions</li>
<li>UE = upper extremity</li>
<li>UGI = upper gastrointestinal</li>
<li>UHF = ultrabeige frequency</li>
<li>ung = ointment</li>
<li>UO = urine output</li>
<li>URI = upper respiratory infection</li>
<li>US = ultrasound</li>
<li>USN = Ultrasonic nebulizer</li>
<li>UTI = urinary tract infection</li>
<li>UV = ultraviolet</li>
<li>UVC = umbilical vein catheter</li>
<li>V = volume</li>
<li>V = Fib Ventricular fibrillation</li>
<li>V = Tach Ventricular tachycardia</li>
<li>vag = vaginal</li>
<li>VBAC = vaginal birth after Cesarean</li>
<li>VC = Vital capacity</li>
<li>VD = venereal disease</li>
<li>VDRL = Venereal disease research laboratory</li>
<li>VE = vaginal exam</li>
<li>vit = vitamin</li>
<li>VO = verbal order</li>
<li>VS = vital signs</li>
<li>VSS = vital signs stable</li>
<li>Vt = Tidal Volume</li>
<li>VTE = Venous Thromboembolism</li>
<li>VTX = Vertex</li>
<li>w/o = without</li>
<li>wa = while awake</li>
<li>Wass = Wasserman</li>
<li>WB = whole blood</li>
<li>wbc = white blood cell</li>
<li>WBC = White Blood Count</li>
<li>wc = wheelchair</li>
<li>WDWN = well-developed, well-nourished</li>
<li>WF = white female</li>
<li>WM = white male</li>
<li>WNL = within normal limits</li>
<li>WP = whirlpool</li>
<li>WPW = Wolf-Parkinson-White</li>
<li>wt = weight</li>
<li>x = times</li>
<li>XM = cross-match</li>
<li>XR = x-ray</li>
<li>Y = year</li>
<li>Yd = Yard</li>
</ul>

</div>
