<ul class="app-navbar-menu-list">
    <li><a href="/allergies">Allergies</a></li>        
    <li><a href="/anaphylaxis">Anaphylaxis</a></li>
    <li><a href="/antiphospholipid-syndrome">Antiphospholipid syndrome (APS)</a></li>
    <li><a href="/asthma">Asthma</a></li>
    <li><a href="/burning-mouth-syndrome">Burning mouth syndrome (BMS)</a></li>
    <li><a href="/dysautonomia">Dysautonomia</a></li>
    <li><a href="/ehlers-danlos-syndrome">Ehlers-Danlos syndrome</a></li>
    <li><a href="/eosinophilic-esophagitis">Eosinophilic esophagitis (EoE)</a></li>
    <li><a href="/ferroptosis">Ferroptosis</a></li>
    <li><a href="/gastroesophageal-reflux-disease">Gastroesophageal Reflux Disease (GERD)</a></li>
    <li><a href="/histamine-intolerance">Histamine intolerance</a></li>
    <li><a href="/lyme-disease">Lyme disease</a></li>
    <li><a href="/mast-cell-activation-syndrome">Mast cell activation syndrome (MACS)</a></li>
    <li><a href="/mastocytosis">Mastocytosis</a></li>
    <li><a href="/multisystem-inflammatory-syndrome">Multisystem Inflammatory Syndrome (MIS)</a></li>
    <li><a href="/postural-orthostatic-tachycardia-syndrome">Postural Orthostatic Tachycardia Syndrome (POTS)</a></li>
    <li><a href="/rheumatoid-arthritis">Rheumatoid arthritis (RA)</a></li>
    <li><a href="/sulfur-intolerance">Sulfur intolerance</a></li>
    <li><a href="/telangiectasia-macularis-eruptiva-perstans">Telangiectasia Macularis Eruptiva Perstans</a></li>
    <li><a href="/toxin-exposure">Toxin exposure</a></li>
</ul>
