<svelte:head>
    <title>Complement C3 protein | mastcell.help | mastcell.help</title>
</svelte:head>

<div class="prose">

<h1 id="complement-c3-protein">Complement C3 protein</h1>
<p>Complement C3 is a crucial protein in the complement system, a part of the immune system that helps the body fight infections and clear away damaged cells. C3 is a central component of the complement cascade, which consists of a series of proteins that work together to recognize and eliminate pathogens, opsonize (mark for destruction) microbes, and induce inflammatory responses.</p>
<p><strong>Functions</strong>:</p>
<ul>
<li><p><strong>Opsonization</strong>: C3b binds to the surface of pathogens and immune complexes, marking them for recognition and phagocytosis by phagocytic cells (e.g., macrophages, neutrophils).</p></li>
<li><p><strong>Inflammation</strong>: C3a and C5a, generated by the cleavage of C3 and C5, respectively, act as anaphylatoxins, inducing the release of inflammatory mediators and recruiting immune cells to the site of infection.</p></li>
<li><p><strong>Membrane Attack Complex (MAC) Formation</strong>: C3b participates in the assembly of the MAC, a pore-forming complex that inserts into the membrane of target cells, leading to cell lysis and destruction of pathogens.</p></li>
</ul>
<p><strong>Activation pathways</strong>:</p>
<ul>
<li><p><strong>Classical Pathway</strong>: Activation occurs when complement protein C1 binds to antibodies attached to the surface of pathogens, leading to the sequential cleavage of C4 and C2 and the formation of the C3 convertase (C4b2a), which cleaves C3 into C3a and C3b.</p></li>
<li><p><strong>Alternative Pathway</strong>: Activation occurs spontaneously when C3 undergoes a slow hydrolysis reaction, generating C3(H2O), which can bind to factors B and D to form the alternative pathway C3 convertase (C3(H2O)Bb), leading to further cleavage of C3.</p></li>
<li><p><strong>Lectin Pathway</strong>: Activation occurs when mannose-binding lectin (MBL) or ficolins bind to carbohydrate structures on the surface of pathogens, leading to the recruitment of MBL-associated serine proteases (MASPs) and the formation of the lectin pathway C3 convertase (C4b2a).</p></li>
</ul>

</div>
